### ISSUE TITLE
SBMLToolkit and Catalyst Warnings

### ISSUE THREAD

**Issue by NikosMemmos** [paulflang/SbmlToolkit.jl#146]
I am importing an SBML file without a problem but I got the following warnings:

`Warning: Stoichiometries of SpeciesReferences are not defined. Setting to 1.
`
`WARNING: both Symbolics and ModelingToolkit export “supremum”; uses of it in module Catalyst must be qualified
`
`WARNING: both Symbolics and ModelingToolkit export “infimum”; uses of it in module Catalyst must be qualified
`

Here is the code:

```
using DifferentialEquations
using SBMLToolkit
using ModelingToolkit

SBMLToolkit.checksupport_file("toy_model_sbml.xml");
mdl = readSBML("toy_model_sbml.xml");
rn = ReactionSystem(mdl);
```

I generate the SBML file using BioNetGen.

**Comment by TorkelE** [comment]
I do not know about the former one (but maybe @paulflang does). These two:
```
WARNING: both Symbolics and ModelingToolkit export “supremum”; uses of it in module Catalyst must be qualified 
WARNING: both Symbolics and ModelingToolkit export “infimum”; uses of it in module Catalyst must be qualified
```
can be safely ignored.

**Comment by paulflang** [comment]
Could it be that your sbml is not level 3 version 2? Maybe try using `readSBML` in one of the ways that are described in the readme. The way you are using it now is not handling version conversion and a couple of other things that are needed.

**Comment by NikosMemmos** [comment]
> Could it be that your sbml is not level 3 version 2? Maybe try using `readSBML` in one of the ways that are described in the readme. The way you are using it now is not handling version conversion and a couple of other things that are needed.

When I switch from:
`mdl = readSBML("toy_model_sbml.xml");
`

to:

```
mdl = readSBML("toy_model_sbml.xml", doc -> begin
    set_level_and_version(3, 2)(doc)
    convert_promotelocals_expandfuns(doc)
end);
```

I only get the last two warnings when I create the reaction system. Thanks for your reply!

**Comment by paulflang** [comment]
No worries. If you never need the SBML.Model, just use `rs = readSBML("toy_model_sbml.xml", ReactionSystemImporter())`; and if the only thing you ever need is the ModelingToolkit.ODESystem, just use `odesys = readSBML("toy_model_sbml.xml", ODESystemImporter())`.

Anyway, I am closing this issue. Feel free to reopen if you have further difficulties.
