### ISSUE TITLE
Do we need docs in CI workflow?

### ISSUE THREAD

**Issue by paulflang** [paulflang/SbmlToolkit.jl#67]
https://github.com/SciML/SBMLToolkit.jl/actions/runs/2402566152/workflow#L45

We do not have a documentation page, as we are just using the readme. Can we get rid of the docs in ci @anandijain?

**Comment by anandijain** [comment]
yeah unless you wanna put it together, but i feel like usage is pretty self explanatory

**Comment by paulflang** [comment]
fixed with fd24440f3aaf92a8762bb6f0e1c4fe6a2ad5e2a4
