### ISSUE TITLE
ERROR: "Incremental compilation may be fatally broken for this module" error

### ISSUE THREAD

**Issue by NikosMemmos** [paulflang/SbmlToolkit.jl#96]
I recently updated the packages in Julia and SBMLToolkit stopped working (see attached image). 

The final error is: ERROR: LoadError: Base.Meta.ParseError("unknown property type irreducible") 

It used to work well before that. Do you have any ideas why this is happening? Thank you for your help in advance!

![error](https://user-images.githubusercontent.com/70726352/201793393-7592cea1-3cc8-4496-9719-b376130effac.png)

**Comment by ChrisRackauckas** [comment]
Remove DiffEqJump. That package was deprecated awhile ago.
